### ISSUE TITLE
Add retroactivity time limit 

### ISSUE THREAD

**Issue by vassalloandrea** [solidusio-contrib/solidus_abandoned_carts#17]
The `abandoned` scope limits the orders to send the abandoned cart email after a period of time using the `timeout` configuration.

Add the ability to limit the orders to restrict the retroactivity adding another configurable filter to the same scope.

https://github.com/solidusio-contrib/solidus_abandoned_carts/blob/981dfe419a56e89295864af89769a2f27898d2c1/app/decorators/models/spree/order_decorator.rb#L7

**Comment by jtapia** [comment]
@vassalloandrea something like this https://github.com/solidusio-contrib/solidus_abandoned_carts/pull/20?

**Comment by vassalloandrea** [comment]
> @vassalloandrea something like this #20?

Not exactly :D I want to set the retroactivity limit avoiding that an application that works for a long time sends emails to a very old abandoned cart!

For example:

E-Commerce that works for 3-4 years should have the ability to add this extension setting a range of dates to send the abandoned cart only for orders that were created recently.
